services:
  postgres:
    image: postgres:17
    container_name: alphabrief-postgres
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - alphabrief_pg_data:/var/lib/postgresql/data

volumes:
  alphabrief_pg_data:
